function [ output_data ] = convertBipolar2UnipolarBasic( signalHeader,signalCell,range)
bipolar_label={'FP1-F7' 'F7-T7' 'T7-P7' 'P7-O1' 'FP1-F3' 'F3-C3' 'C3-P3' 'P3-O1' 'FP2-F4' 'F4-C4' 'C4-P4' 'P4-O2' 'FP2-F8' 'F8-T8' 'T8-P8' 'P8-O2' 'FZ-CZ' 'CZ-PZ' 'T7-FT9' 'FT9-FT10' 'FT10-T8'}';

unipolar_channels={'AF7','AF3','AF4','AF8','FT7','FC3','FCz','FC4','FT8','T7','T8','TP7','CP3','CPZ','CP4','TP8','PO7','PO3','PO4','PO8'}';




unipolar_reference={{'AF7','FP1-F7'},...
                    {'AF3','FP1-F3'},...
                    {'AF4','FP2-F4'},...
                    {'AF8','FP2-F8'},...
                    {'FT7','F7-T7'},...
                    {'FC3','F3-C3'},...
                    {'FCz','FZ-CZ'},...
                    {'FC4','F4-C4'},...
                    {'FT8','F8-T8'},...
                    {'T7','T7-FT9'},...
                    {'T8','FT10-T8'},...
                    {'TP7','T7-P7'},...
                    {'CP3','C3-P3'},...
                    {'CPZ','CZ-PZ'},...
                    {'CP4','C4-P4'},...
                    {'TP8','T8-P8'},...
                    {'PO7','P7-O1'},...
                    {'PO3','P3-O1'},...
                    {'PO4','P4-O2'},...
                    {'PO8','P8-O2'},...
                    }';
                
signal_labels=struct2cell(signalHeader');
signal_labels=signal_labels(1,:);
if isempty(range)
  signal_len = size(signalCell{1},1);
  range(1)=1;
  range(2)=signal_len;
else
  signal_len = range(2)-range(1);
end

                               
output_data=unipolar_channels;

for i=1:size(unipolar_channels,1)
    index= find(strcmp(signal_labels,unipolar_reference{i}(2)));
    output_index= find(strcmp(output_data(:,1),unipolar_reference{i}(1)));
    output_data{output_index,2}=signalCell{index(1)}(range(1):range(2));
end

end

