function [ output_data ] = convertBipolar2Unipolar( signalHeader,signalCell,range)
bipolar_label={'FP1-F7' 'F7-T7' 'T7-P7' 'P7-O1' 'FP1-F3' 'F3-C3' 'C3-P3' 'P3-O1' 'FP2-F4' 'F4-C4' 'C4-P4' 'P4-O2' 'FP2-F8' 'F8-T8' 'T8-P8' 'P8-O2' 'FZ-CZ' 'CZ-PZ' 'T7-FT9' 'FT9-FT10' 'FT10-T8'}';
reference_channels={'FT9','PZ'}';

unipolar_channels={'T7','F7','FP1','P7','O1','P3','C3','F3','FT10','T8','F8','FP2','P8','O2','P4','C4','F4','CZ','FZ','FT9','PZ'}';
unipolar_reference={{'T7','FT9','+','T7-FT9'},...
                    {'F7','T7','+','F7-T7'}...
                    {'FP1','F7','+','FP1-F7'}...
                    {'P7','T7','-','T7-P7'}...
                    {'O1','P7','-','P7-O1'}...
                    {'P3','O1','+','P3-O1'}...
                    {'C3','P3','+','C3-P3'}...
                    {'F3','C3','+','F3-C3'}...
                    {'FT10','FT9','-','FT9-FT10'}...
                    {'T8','FT10','-','FT10-T8'}...
                    {'F8','T8','+','F8-T8'}...
                    {'FP2','F8','+','FP2-F8'}...
                    {'P8','T8','-','T8-P8'}...
                    {'O2','P8','-','P8-O2'}...
                    {'P4','O2','+','P4-O2'}...
                    {'C4','P4','+','C4-P4'}...
                    {'F4','C4','+','F4-C4'}...
                    {'CZ','PZ','+','CZ-PZ'}...
                    {'FZ','CZ','+','FZ-CZ'}...
                    }';
                
signal_labels=struct2cell(signalHeader');
signal_labels=signal_labels(1,:);
if isempty(range)
  signal_len = size(signalCell{1},1);
  range(1)=1;
  range(2)=signal_len+1;
else
  signal_len = range(2)-range(1);
end



                               
output_data=unipolar_channels;
output_data{1,2}=[];
for i=1:size(reference_channels,1)
    index= find(not(cellfun('isempty', strfind(output_data(:,1),reference_channels{i}))),1);
    output_data{index,2}=zeros(signal_len,1);
end

for i=1:size(unipolar_channels,1)-size(reference_channels,1)
    index= find(not(cellfun('isempty', strfind(signal_labels,unipolar_reference{i}(4)))),1);
    ref_index=find(not(cellfun('isempty', strfind(output_data(:,1),unipolar_reference{i}(2)))),1);
    if isequal(unipolar_reference{i}(3),{'+'})
        new_channel=output_data{ref_index,2}+signalCell{index}(range(1):range(2)-1);
    else
        new_channel=output_data{ref_index,2}-signalCell{index}(range(1):range(2)-1);
    end
    output_index= find(not(cellfun('isempty', strfind(output_data(:,1),unipolar_reference{i}(1)))),1);
    output_data{output_index,2}=new_channel;
end

end

